// СГЕНЕРИРОВАНО `make kernel` из kernel/biot.wasm. Руками не правят.
//
// Блоб лежит в исходнике, а не отдельным файлом: симулятор собирается в один
// html (scripts/build_sim.py) и обязан открываться двойным кликом, а отдельный
// файл пришлось бы тянуть запросом.
//
// Размер решает способ загрузки. Браузеры запрещают синхронную компиляцию в
// главном потоке на буферах больше ЧЕТЫРЁХ килобайт: кто под лимитом — грузится
// сразу, кто нет — асинхронно, а до готовности считает откат на JS. Стоит это
// ровно ничего, потому что откат даёт побитово тот же ответ.
export const BIOT_WASM_B64 =
  'AGFzbQEAAAABFgNgCX9/f39/f39/fwBgAX8Bf2AAAX8DBQQAAAECBAUBcAEBAQUEAQCAAgYIAX8BQYCABAsHSQYGbWVtb3J5' +
  'AgAPX19zdGFja19wb2ludGVyAwALZmllbGRfZWRnZXMAAAh0YWlsc19hdAABBWFsbG9jAAIJaGVhcF91c2VkAAMK+hQE2QwF' +
  'BX8Bew1/FHsOfAJAIAVBAUgNAEEAIQkCQCAFQQxJDQAgByAGa0EQSQ0AIAggBmtBEEkNACAIIAdrQRBJDQAgBiEKIAchCyAI' +
  'IQwgBUH+////B3EiCSENA0AgCv0MAAAAAAAAAAAAAAAAAAAAACIO/QsDACALIA79CwMAIAwgDv0LAwAgCkEQaiEKIAtBEGoh' +
  'CyAMQRBqIQwgDUF+aiINDQALIAUgCUYNAQsgCSEPAkAgBSAJa0EDcSINRQ0AIAkgDWohDyAGIAlBA3QiDGohCiAHIAxqIQsg' +
  'CCAMaiEMA0AgCkIANwMAIAtCADcDACAMQgA3AwAgCkEIaiEKIAtBCGohCyAMQQhqIQwgDUF/aiINDQALCyAJIAVrQXxLDQAg' +
  'D0EDdCENIAUgD2shECAGIQkgByEPIAghEQNAIAkgDWoiCkIANwMAIA8gDWoiC0IANwMAIBEgDWoiDEIANwMAIApBCGpCADcD' +
  'ACALQQhqQgA3AwAgDEEIakIANwMAIApBEGpCADcDACALQRBqQgA3AwAgDEEQakIANwMAIApBGGpCADcDACALQRhqQgA3AwAg' +
  'DEEYakIANwMAIAlBIGohCSAPQSBqIQ8gEUEgaiERIBBBfGoiEA0ACwsCQCABQQFIDQAgBUF+cSESIAIgBUEDdEFwcSIKaiET' +
  'IAMgCmohFCAEIApqIRUgBiAKaiEWIAcgCmohFyAIIApqIRhBACEZIAVBAkghGkEAIRsDQCAAIBtBA3RqIQoCQCAaDQAgCv0K' +
  'AzAhHCAK/QoDKCEdIAr9CgMgIR4gCv0KAxghHyAK/QoDECEgIAr9CgMIISEgCv0KAwAhIiAKKwM4/RQhI0EAIRAgAiEJIAMh' +
  'DyAEIREgBiELIAchDCAIIQ0DQCALIAv9AAMAIAn9AAMAICL98QEiDiAP/QADACAh/fEBIiQgHv3xASIl/fIBIA4gH/3xASIm' +
  'ICT98gH98QEiJyAn/fIBICQgEf0AAwAgIP3xASIoIB398QEiKf3yASAlICj98gH98QEiKiAq/fIBICYgKP3yASAOICn98gH9' +
  '8QEiKyAr/fIB/fAB/fABIiz9DLu919nffNs9u73X2d982z0iLf1MIA4gDv3yASAkICT98gH98AEgKCAo/fIB/fAB/e8BIi4g' +
  'Lf1M/U4gJiAm/fIBICUgJf3yAf3wASApICn98gH98AH97wEiLyAt/Uz9TiItIBwgKiAfIA798gEgHiAk/fIB/fABIB0gKP3y' +
  'Af3wASAu/fMBIB8gJv3yASAeICX98gH98AEgHSAp/fIB/fABIC/98wH98QEgIyAs/fcB/QwYLURU+yEpQBgtRFT7ISlA/fIB' +
  '/fMBIg798gH98gH9Tv3wAf0LAwAgDCAM/QADACAtIBwgKyAO/fIB/fIB/U798AH9CwMAIA0gDf0AAwAgLSAcICcgDv3yAf3y' +
  'Af1O/fAB/QsDACAJQRBqIQkgD0EQaiEPIBFBEGohESALQRBqIQsgDEEQaiEMIA1BEGohDSAQQQJqIhAgEkgNAAsLIBMhCyAU' +
  'IQwgFSENIBYhCSAXIQ8gGCERIBIhEAJAIBIgBUYNAANAAkAgCysDACAKKwMAoSIwIAwrAwAgCisDCKEiMSAKKwMgIjKhIjOi' +
  'IDEgMCAKKwMYIjShIjWioSI2IDaiIDEgDSsDACAKKwMQoSI3IAorAygiOKEiOaIgNyAzoqEiOiA6oiA3IDWiIDAgOaKhIjsg' +
  'O6KgoCI8RLu919nffNs9Yw0AIDD9FCA1/SIBIg4gDv3yASAx/RQgM/0iASIOIA798gH98AEgN/0UIDn9IgEiDiAO/fIB/fAB' +
  '/e8BIg79DLu919nffNs9u73X2d982z39SSIk/R0AICT9HQGEp0EBcQ0AIAkgCSsDACAKKwMwIj0gOiAwIDSiIDEgMqKgIDcg' +
  'OKKgIA79IQCjIDQgNaIgMiAzoqAgOCA5oqAgDv0hAaOhIDwgCisDOCIwIDwgMGQbRBgtRFT7ISlAoqMiMKKioDkDACAPIA8r' +
  'AwAgPSA7IDCioqA5AwAgESARKwMAID0gNiAwoqKgOQMACyALQQhqIQsgDEEIaiEMIA1BCGohDSAJQQhqIQkgD0EIaiEPIBFB' +
  'CGohESAQQQFqIhAgBUgNAAsLIBtBCGohGyAZQQFqIhkgAUcNAAsLC+EHBQt/CHsHfwl7DHwCQCABQQFIDQAgBUF+cSEJIAIg' +
  'BUEDdEFwcSIKaiELIAMgCmohDCAEIApqIQ0gBiAKaiEOIAcgCmohDyAIIApqIRBBACERIAVBAkghEkEAIRMDQCAAIBNBA3Rq' +
  'IQoCQCASDQAgCv0KAzAhFCAK/QoDKCEVIAr9CgMgIRYgCv0KAxghFyAK/QoDECEYIAr9CgMIIRkgCv0KAwAhGiAKKwM4/RQh' +
  'G0EAIRwgAiEdIAMhHiAEIR8gBiEgIAchISAIISIDQCAgICD9AAMAIBcgHv0AAwAgGf3xASIj/fIBIBYgHf0AAwAgGv3xASIk' +
  '/fIB/fEBIiUgJf3yASAWIB/9AAMAIBj98QEiJv3yASAVICP98gH98QEiJyAn/fIBIBUgJP3yASAXICb98gH98QEiKCAo/fIB' +
  '/fAB/fABIin9DLu919nffNs9u73X2d982z0iKv1MICQgJP3yASAjICP98gH98AEgJiAm/fIB/fAB/e8BIisgKv1M/U4iKiAU' +
  'ICcgFyAk/fIBIBYgI/3yAf3wASAVICb98gH98AEgK/3zAf0MAAAAAAAA8D8AAAAAAADwP/3wASAbICn99wH9DBgtRFT7ISlA' +
  'GC1EVPshKUD98gH98wEiI/3yAf3yAf1O/fAB/QsDACAhICH9AAMAICogFCAoICP98gH98gH9Tv3wAf0LAwAgIiAi/QADACAq' +
  'IBQgJSAj/fIB/fIB/U798AH9CwMAIB1BEGohHSAeQRBqIR4gH0EQaiEfICBBEGohICAhQRBqISEgIkEQaiEiIBxBAmoiHCAJ' +
  'SA0ACwsgCyEgIAwhISANISIgDiEdIA8hHiAQIR8gCSEcAkAgCSAFRg0AA0ACQCAhKwMAIAorAwihIiwgCisDGCItoiAgKwMA' +
  'IAorAwChIi4gCisDICIvoqEiMCAwoiAiKwMAIAorAxChIjEgL6IgLCAKKwMoIjKioSIzIDOiIC4gMqIgLSAxoqEiNCA0oqCg' +
  'IjVEu73X2d982z1jDQAgLiAuoiAsICyioCAxIDGioJ8iNkS7vdfZ33zbPWMNACAdIB0rAwAgCisDMCI3IDMgLiAtoiAsIC+i' +
  'oCAxIDKioCA2o0QAAAAAAADwP6AgNSAKKwM4IiwgNSAsZBtEGC1EVPshKUCioyIsoqKgOQMAIB4gHisDACA3IDQgLKKioDkD' +
  'ACAfIB8rAwAgNyAwICyioqA5AwALICBBCGohICAhQQhqISEgIkEIaiEiIB1BCGohHSAeQQhqIR4gH0EIaiEfIBxBAWoiHCAF' +
  'SA0ACwsgE0EIaiETIBFBAWoiESABRw0ACwsLLgEBf0EAQQAoAoCAhIAAIgFBkICEgAAgARtBD2pBcHEiASAAajYCgICEgAAg' +
  'AQsLAEEAKAKAgISAAAsAUgRuYW1lAAoJYmlvdC53YXNtASsEAAtmaWVsZF9lZGdlcwEIdGFpbHNfYXQCBmthbGxvYwMJaGVh' +
  'cF91c2VkBxIBAA9fX3N0YWNrX3BvaW50ZXIALwlwcm9kdWNlcnMBDHByb2Nlc3NlZC1ieQEOSG9tZWJyZXcgY2xhbmcGMjIu' +
  'MS44AJ0BD3RhcmdldF9mZWF0dXJlcwkrC2J1bGstbWVtb3J5Kw9idWxrLW1lbW9yeS1vcHQrFmNhbGwtaW5kaXJlY3Qtb3Zl' +
  'cmxvbmcrCm11bHRpdmFsdWUrD211dGFibGUtZ2xvYmFscysTbm9udHJhcHBpbmctZnB0b2ludCsPcmVmZXJlbmNlLXR5cGVz' +
  'KwhzaWduLWV4dCsHc2ltZDEyOA==';
