// СГЕНЕРИРОВАНО `make kernel` из kernel/biot.wasm. Руками не правят.
//
// Блоб лежит в исходнике, а не отдельным файлом, по двум причинам: симулятор
// собирается в один html (scripts/build_sim.py), и отдельный файл пришлось бы
// тянуть запросом; а два килобайта base64 дешевле, чем развилка загрузки.
export const BIOT_WASM_B64 =
  'AGFzbQEAAAABFgNgCX9/f39/f39/fwBgAX8Bf2AAAX8DBAMAAQIEBQFwAQEBBQQBAIACBggBfwFBgIAECwc+BQZtZW1vcnkC' +
  'AA9fX3N0YWNrX3BvaW50ZXIDAAtmaWVsZF9lZGdlcwAABWFsbG9jAAEJaGVhcF91c2VkAAIKlw0D2QwFBX8Bew1/FHsOfAJA' +
  'IAVBAUgNAEEAIQkCQCAFQQxJDQAgByAGa0EQSQ0AIAggBmtBEEkNACAIIAdrQRBJDQAgBiEKIAchCyAIIQwgBUH+////B3Ei' +
  'CSENA0AgCv0MAAAAAAAAAAAAAAAAAAAAACIO/QsDACALIA79CwMAIAwgDv0LAwAgCkEQaiEKIAtBEGohCyAMQRBqIQwgDUF+' +
  'aiINDQALIAUgCUYNAQsgCSEPAkAgBSAJa0EDcSINRQ0AIAkgDWohDyAGIAlBA3QiDGohCiAHIAxqIQsgCCAMaiEMA0AgCkIA' +
  'NwMAIAtCADcDACAMQgA3AwAgCkEIaiEKIAtBCGohCyAMQQhqIQwgDUF/aiINDQALCyAJIAVrQXxLDQAgD0EDdCENIAUgD2sh' +
  'ECAGIQkgByEPIAghEQNAIAkgDWoiCkIANwMAIA8gDWoiC0IANwMAIBEgDWoiDEIANwMAIApBCGpCADcDACALQQhqQgA3AwAg' +
  'DEEIakIANwMAIApBEGpCADcDACALQRBqQgA3AwAgDEEQakIANwMAIApBGGpCADcDACALQRhqQgA3AwAgDEEYakIANwMAIAlB' +
  'IGohCSAPQSBqIQ8gEUEgaiERIBBBfGoiEA0ACwsCQCABQQFIDQAgBUF+cSESIAIgBUEDdEFwcSIKaiETIAMgCmohFCAEIApq' +
  'IRUgBiAKaiEWIAcgCmohFyAIIApqIRhBACEZIAVBAkghGkEAIRsDQCAAIBtBA3RqIQoCQCAaDQAgCv0KAzAhHCAK/QoDKCEd' +
  'IAr9CgMgIR4gCv0KAxghHyAK/QoDECEgIAr9CgMIISEgCv0KAwAhIiAKKwM4/RQhI0EAIRAgAiEJIAMhDyAEIREgBiELIAch' +
  'DCAIIQ0DQCALIAv9AAMAIAn9AAMAICL98QEiDiAP/QADACAh/fEBIiQgHv3xASIl/fIBIA4gH/3xASImICT98gH98QEiJyAn' +
  '/fIBICQgEf0AAwAgIP3xASIoIB398QEiKf3yASAlICj98gH98QEiKiAq/fIBICYgKP3yASAOICn98gH98QEiKyAr/fIB/fAB' +
  '/fABIiz9DLu919nffNs9u73X2d982z0iLf1MIA4gDv3yASAkICT98gH98AEgKCAo/fIB/fAB/e8BIi4gLf1M/U4gJiAm/fIB' +
  'ICUgJf3yAf3wASApICn98gH98AH97wEiLyAt/Uz9TiItIBwgKiAfIA798gEgHiAk/fIB/fABIB0gKP3yAf3wASAu/fMBIB8g' +
  'Jv3yASAeICX98gH98AEgHSAp/fIB/fABIC/98wH98QEgIyAs/fcB/QwYLURU+yEpQBgtRFT7ISlA/fIB/fMBIg798gH98gH9' +
  'Tv3wAf0LAwAgDCAM/QADACAtIBwgKyAO/fIB/fIB/U798AH9CwMAIA0gDf0AAwAgLSAcICcgDv3yAf3yAf1O/fAB/QsDACAJ' +
  'QRBqIQkgD0EQaiEPIBFBEGohESALQRBqIQsgDEEQaiEMIA1BEGohDSAQQQJqIhAgEkgNAAsLIBMhCyAUIQwgFSENIBYhCSAX' +
  'IQ8gGCERIBIhEAJAIBIgBUYNAANAAkAgCysDACAKKwMAoSIwIAwrAwAgCisDCKEiMSAKKwMgIjKhIjOiIDEgMCAKKwMYIjSh' +
  'IjWioSI2IDaiIDEgDSsDACAKKwMQoSI3IAorAygiOKEiOaIgNyAzoqEiOiA6oiA3IDWiIDAgOaKhIjsgO6KgoCI8RLu919nf' +
  'fNs9Yw0AIDD9FCA1/SIBIg4gDv3yASAx/RQgM/0iASIOIA798gH98AEgN/0UIDn9IgEiDiAO/fIB/fAB/e8BIg79DLu919nf' +
  'fNs9u73X2d982z39SSIk/R0AICT9HQGEp0EBcQ0AIAkgCSsDACAKKwMwIj0gOiAwIDSiIDEgMqKgIDcgOKKgIA79IQCjIDQg' +
  'NaIgMiAzoqAgOCA5oqAgDv0hAaOhIDwgCisDOCIwIDwgMGQbRBgtRFT7ISlAoqMiMKKioDkDACAPIA8rAwAgPSA7IDCioqA5' +
  'AwAgESARKwMAID0gNiAwoqKgOQMACyALQQhqIQsgDEEIaiEMIA1BCGohDSAJQQhqIQkgD0EIaiEPIBFBCGohESAQQQFqIhAg' +
  'BUgNAAsLIBtBCGohGyAZQQFqIhkgAUcNAAsLCy4BAX9BAEEAKAKAgISAACIBQZCAhIAAIAEbQQ9qQXBxIgEgAGo2AoCAhIAA' +
  'IAELCwBBACgCgICEgAALAEgEbmFtZQAKCWJpb3Qud2FzbQEhAwALZmllbGRfZWRnZXMBBmthbGxvYwIJaGVhcF91c2VkBxIB' +
  'AA9fX3N0YWNrX3BvaW50ZXIALwlwcm9kdWNlcnMBDHByb2Nlc3NlZC1ieQEOSG9tZWJyZXcgY2xhbmcGMjIuMS44AJ0BD3Rh' +
  'cmdldF9mZWF0dXJlcwkrC2J1bGstbWVtb3J5Kw9idWxrLW1lbW9yeS1vcHQrFmNhbGwtaW5kaXJlY3Qtb3ZlcmxvbmcrCm11' +
  'bHRpdmFsdWUrD211dGFibGUtZ2xvYmFscysTbm9udHJhcHBpbmctZnB0b2ludCsPcmVmZXJlbmNlLXR5cGVzKwhzaWduLWV4' +
  'dCsHc2ltZDEyOA==';
